Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/08/2023
Var
// Seção de Declarações das variáveis 
nota1, nota2, :real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("nota1")
 leia(nota1)
 escreva("nota2")
 leia(nota2)

Fimalgoritmo