Algoritmo "numero de 1 a 5"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2023
Var
// Seção de Declarações das variáveis 
 i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   para i de 1 ate 1000000 faca
    escreval("O valor do número é:", i)
   fimpara
   


Fimalgoritmo