Algoritmo "soma"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/08/2023
Var
// Seção de Declarações das variáveis 
a, b,  c:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  a<-2
  b<-3
  c<-a+b
  escreva(c)
  
  

Fimalgoritmo